<a href="https://colab.research.google.com/github/pramod1997/Deep_Learning_Assignments/blob/master/DL_Assgn_1_Ques_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
### design XOR problem using ANN
### define the backprop itself 

## 0 0 0
## 1 1 0
## 1 0 1
## 0 1 1

## using tanh function 


In [0]:
import numpy as np 
import matplotlib.pyplot as plt
import sys

In [0]:
### training data
X = np.array([
    [-1,-1],
    [1,1],
    [-1,1],
    [1,-1]
])
y = np.array([
    [-1],
    [-1],
    [1],
    [1]
])

In [0]:
### designing very simple MLP 
## no of input nuerons --> 2
##hiddnen layer -->1
## hidden layer unit -->2 
### no of output layers  ----> 1 

In [0]:
num_i_units = 2 # Number of Input units
num_h_units = 2 # Number of Hidden units
num_o_units = 1 # Number of Output units

In [0]:
# The learning rate for Gradient Descent.
learning_rate = 0.01

# The parameter to help with overfitting.
reg_param = 0

# Maximum iterations for Gradient Descent.
max_iter = 6000

# Number of training examples
m = 4

In [0]:
### Nueral net some info --> weights will be generated using random distribution using numpy --> gives horrible result sometimes

In [0]:
np.random.seed(1)
W1 = np.random.normal(-1, 1, (num_h_units, num_i_units)) # 2x2
W2 = np.random.normal(-1, 1, (num_o_units, num_h_units)) # 1x2

B1 = np.random.random((num_h_units, 1)) # 2x1
B2 = np.random.random((num_o_units, 1)) # 1x1

In [8]:
W1

array([[ 0.62434536, -1.61175641],
       [-1.52817175, -2.07296862]])

In [9]:
W2

array([[-0.13459237, -3.3015387 ]])

In [10]:
B1

array([[0.41919451],
       [0.6852195 ]])

In [11]:
B2

array([[0.20445225]])

In [0]:
def tanh(z, derv=False):
    if derv: return 1 - np.tanh(z)*np.tanh(z)
    #return 1 / (1 + np.exp(-z))
    return np.tanh(z)
                

In [0]:
def forward(x, predict=False):
    a1 = x.reshape(x.shape[0], 1) # Getting the training example as a column vector.

    z2 = W1.dot(a1) + B1 # 2x2 * 2x1 + 2x1 = 2x1
    a2 = tanh(z2) # 2x1

    z3 = W2.dot(a2) + B2 # 1x2 * 2x1 + 1x1 = 1x1
    a3 = tanh(z3)

    if predict: return a3
    return (a1, a2, a3)

In [0]:
dW1 = 0 # Gradient for W1
dW2 = 0 # Gradient for W2

dB1 = 0 # Gradient for B1
dB2 = 0 # Gradient for B2

cost = np.zeros((max_iter, 1)) # Column vector to record the cost of the NN after each Gradient Descent iteration.

In [0]:
def train(_W1, _W2, _B1, _B2): # The arguments are to bypass UnboundLocalError error
    for i in range(max_iter):
        c = 0
        
        dW1 = 0
        dW2 = 0

        dB1 = 0
        dB2 = 0
        
        for j in range(m):
            sys.stdout.write("\rIteration: {} and {}".format(i + 1, j + 1))

            # Forward Prop.
            a0 = X[j].reshape(X[j].shape[0], 1) # 2x1

            z1 = _W1.dot(a0) + _B1 # 2x2 * 2x1 + 2x1 = 2x1
            a1 = tanh(z1) # 2x1

            z2 = _W2.dot(a1) + _B2 # 1x2 * 2x1 + 1x1 = 1x1
            a2 = tanh(z2) # 1x1

            # Back prop.
            dz2 = a2 - y[j] # 1x1
            dW2 += dz2 * a1.T # 1x1 .* 1x2 = 1x2

            dz1 = np.multiply((_W2.T * dz2), tanh(a1, derv=True)) # (2x1 * 1x1) .* 2x1 = 2x1
            dW1 += dz1.dot(a0.T) # 2x1 * 1x2 = 2x2

            dB1 += dz1 # 2x1
            dB2 += dz2 # 1x1

            c = c + (-(y[j] * np.log(a2)) - ((1 - y[j]) * np.log(1 - a2)))
            sys.stdout.flush() # Updating the text.
        
        _W1 = _W1 - learning_rate * (dW1 / m) + ( (reg_param / m) * _W1)
        _W2 = _W2 - learning_rate * (dW2 / m) + ( (reg_param / m) * _W2)

        _B1 = _B1 - learning_rate * (dB1 / m)
        _B2 = _B2 - learning_rate * (dB2 / m)
        cost[i] = (c / m) + ( 
            (reg_param / (2 * m)) * 
            (
                np.sum(np.power(_W1, 2)) + 
                np.sum(np.power(_W2, 2))
            )
        )
    return (_W1, _W2, _B1, _B2)


In [16]:
W1, W2, B1, B2 = train(W1, W2, B1, B2)

Iteration: 30 and 4

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in log


Iteration: 6000 and 4

In [17]:
W1

array([[-1.5703401 , -1.57407417],
       [-1.07675588, -1.07966074]])

In [18]:
W2

array([[ 2.77792396, -2.89956611]])

In [19]:
B1

array([[ 0.85377398],
       [-0.71487883]])

In [20]:
B2

array([[-1.83879431]])

In [0]:
## prediction --> we know the weights and then easily can multiply and get  the results
##  add a prediction function

In [0]:
def predict(test_array):
  #W.x+b
  #tanh (weight_of hiddenlayer *tanh(first layer nueron weight into input + bias ) + b 
  
  ### reshape the test array so that muktplication can work W.x + b 
  a0 = test_array.reshape(2, 1) # 2x1
  
  #print(a0.shape)
  z1 = W1.dot(a0) + B1 # 2x2 * 2x1 + 2x1 = 2x1
  #print(z1.shape)
  a1 = tanh(z1) # 2x1

  z2 = W2.dot(a1) + B2 # 1x2 * 2x1 + 1x1 = 1x1
  #print(z2.shape)
  a2 = tanh(z2) # 1x1
  
  return a2
  
 





In [23]:
print("Predicted Output:{} Expected Output: {}".format(np.sign(predict(np.array([[-1,-1]]))),-1))

Predicted Output:[[-1.]] Expected Output: -1


In [24]:
print("Predicted Output:{} Expected Output: {}".format(np.sign(predict(np.array([[1,1]]))),-1))

Predicted Output:[[-1.]] Expected Output: -1


In [25]:
print("Predicted Output:{} Expected Output: {}".format(np.sign(predict(np.array([[-1,1]]))),1))

Predicted Output:[[1.]] Expected Output: 1


In [26]:
print("Predicted Output:{} Expected Output: {}".format(np.sign(predict(np.array([[1,-1]]))),1))

Predicted Output:[[1.]] Expected Output: 1
